service ft_malloc {
	i32 test_valid_chunk (0: t_chunk previous, 1: t_chunk chunk),
	void free (0: void ptr),
	void remove_chunk (0: t_bin bin, 1: t_chunk chunk, 2: t_chunk previous),
	void calloc (0: i64 nmemb, 1: i64 size),
	void malloc (0: i64 size),
	void realloc (0: i64 size, 1: void ptr),
	void show_alloc_mem (),
	binary get-pr (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	void print (0: byte s),
	i32 main (),
	void print (0: byte s),
	i32 main (),
	void print (0: byte s),
	i32 main (),
}
