service ft_malloc {
	i32 test_valid_chunk (0: binary previous, 1: binary chunk),
	void free (0: binary ptr),
	void remove_chunk (0: binary bin, 1: binary chunk, 2: binary previous),
	binary calloc (0: i64 nmemb, 1: i64 size),
	binary malloc (0: i64 size),
	binary realloc (0: i64 size, 1: binary ptr),
	void show_alloc_mem (),
	binary get-pr (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	i32 main (),
	void print (0: string s),
	i32 main (),
	void print (0: string s),
	i32 main (),
	void print (0: string s),
	i32 main (),
}
