service libft {
	void fill_buffer (0: byte str, 1: byte c, 2: i32 mode, 3: t_print s),
	void wchar_tobuffer (0: t_print s, 1: binary c),
	i32 ft_atoi (0: byte str),
	byte ft_itoa (0: i32 n),
	i32 ft_dprintf (0: binary format, 1: i32 fd),
	i32 ft_printf (0: binary format),
	i32 ft_sprintf (0: byte str, 1: binary format),
	void ft_vprintf (0: t_print s),
	void ft_putchar (0: byte c),
	void ft_putchar_fd (0: byte c, 1: i32 fd),
	void ft_putendl (0: byte s),
	void ft_putendl_fd (0: byte s, 1: i32 fd),
	void ft_putnbr (0: i32 nb),
	void ft_putnbr_fd (0: i32 fd, 1: i32 n),
	void ft_putstr (0: byte str),
	void ft_putstr_fd (0: byte s, 1: i32 fd),
	void ft_putwchar (0: binary c),
	void ft_putwstr (0: binary wstr),
	byte ft_retsplit (0: byte str, 1: byte c, 2: i32 n),
	i32 get_next_line (0: byte line, 1: binary fd),
	void handle_post_digit (0: i32 i, 1: i32 mode, 2: t_print s),
	void handle_signs (0: t_print s),
	void process_flag (0: t_print s),
	void handle_nb (0: t_print s),
	void pad (0: t_print s),
	void handle_bonus (0: t_print s),
	void handle_special (0: t_print s),
	void handle_zero (0: t_print s),
	void handle_str (0: t_print s),
	void ft_lstadd (0: t_list alst, 1: t_list new),
	void ft_lstdel (0: t_list alst, 1: binary del),
	void ft_lstdelone (0: t_list alst, 1: binary del),
	void ft_lstiter (0: t_list lst, 1: binary f),
	t_list ft_lstmap (0: binary f, 1: t_list lst),
	t_list ft_lstnew (0: i64 content_size, 1: void content),
	binary ft_abs (0: binary n),
	t_equa ft_equanew (0: double a, 1: double b, 2: double x, 3: double y),
	t_vec ft_get_perpendicular_vec (0: t_bool way, 1: t_vec a),
	t_vec ft_getmidcoor (0: t_vec a, 1: t_vec b),
	t_vec ft_vecnew (0: double x, 1: double y),
	void ft_swapvec (0: t_vec a, 1: t_vec b),
	void ft_bzero (0: i64 len, 1: void str),
	void ft_memalloc (0: i64 size),
	void ft_memccpy (0: i32 c, 1: i64 n, 2: void dst, 3: void src),
	void ft_memchr (0: i32 c, 1: i64 n, 2: void s),
	i32 ft_memcmp (0: i64 n, 1: void s1, 2: void s2),
	void ft_memcpy (0: i64 n, 1: void dst, 2: void src),
	void ft_memdel (0: void ap),
	void ft_memmove (0: i64 n, 1: void dst, 2: void src),
	void ft_memset (0: i32 c, 1: i64 len, 2: void str),
	byte ft_chartostr (0: byte c),
	byte ft_chrcstr (0: byte hay, 1: byte needle, 2: byte c),
	byte ft_chrstr (0: byte hay, 1: byte needle),
	i32 ft_isalnum (0: i32 c),
	i32 ft_isalpha (0: i32 c),
	i32 ft_isascii (0: i32 c),
	i32 ft_isdigit (0: i32 c),
	i32 ft_isprint (0: i32 c),
	byte ft_strcat (0: byte s1, 1: byte s2),
	byte ft_strchr (0: byte str, 1: i32 c),
	void ft_strclr (0: byte s),
	i32 ft_strcmp (0: byte s1, 1: byte s2),
	i64 ft_strcount (0: byte haystack, 1: byte needle),
	i32 ft_strcpos (0: byte haystack, 1: byte needle),
	byte ft_strcpy (0: byte dst, 1: byte src),
	byte ft_strcsub (0: byte s, 1: byte c),
	void ft_strdel (0: byte as),
	byte ft_strdup (0: byte src),
	i32 ft_strequ (0: byte s1, 1: byte s2),
	void ft_striter (0: byte s, 1: binary f),
	void ft_striteri (0: byte s, 1: binary f),
	byte ft_strjoin (0: byte s1, 1: byte s2),
	byte ft_strjoin_char (0: byte s1, 1: byte c),
	byte ft_strjoinfree (0: byte s1, 1: byte s2),
	i64 ft_strlcat (0: byte s1, 1: binary s2, 2: i64 size),
	i32 ft_strlen (0: byte str),
	byte ft_strmap (0: binary f, 1: byte s),
	byte ft_strmapi (0: binary f, 1: byte s),
	byte ft_strncat (0: byte s1, 1: byte s2, 2: i64 n),
	i32 ft_strncmp (0: byte s1, 1: byte s2, 2: i64 n),
	byte ft_strncpy (0: byte dst, 1: byte src, 2: i64 n),
	i32 ft_strnequ (0: byte s1, 1: byte s2, 2: i64 n),
	byte ft_strnew (0: i64 size),
	byte ft_strnstr (0: byte haystack, 1: byte needle, 2: i64 len),
	byte ft_strnsub (0: byte s, 1: i32 n),
	byte ft_strrchr (0: byte str, 1: i32 c),
	byte ft_strrev (0: byte str),
	i32 ft_strrpos (0: byte haystack, 1: byte needle),
	byte ft_strsplit (0: byte s, 1: byte c),
	byte ft_strstr (0: byte haystack, 1: byte needle),
	byte ft_strsub (0: byte s, 1: i64 len, 2: binary start),
	byte ft_strtrim (0: byte s),
	i32 ft_tolower (0: i32 c),
	i32 ft_toupper (0: i32 c),
	i64 ft_wstrlen (0: binary wstr),
	binary ft_wstrnsub (0: i32 n, 1: binary s),
}
